import Navbar from "@/components/navbar";
import "./globals.css";  // Add this line

// app/layout.tsx
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <div><Navbar /></div>
                {children}
            </body>
        </html>
    );
}
